_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 4eeded5d-ca9b-4303-acd0-0e410e1c11b8
name: 'ITSEA | Georgia Institute of Technology | Atlanta, GA'
mail: steven.snelgrove@oit.gatech.edu
slogan: ''
page:
  403: /node/3
  404: /node/4
  front: /node/110
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
